### PR TITLE
Add support for outgoing audio calls

### PR DESCRIPTION
**Pull request by robinlinden**
Part of #158

### CODE REVIEW

**Comment by helmutsreinis** [comment]
D/ViewRootImpl@95e82c9[PopupWindow:d89cb82]: dispatchDetachedFromWindow
D/InputTransport: Input channel destroyed: '697ed66', fd=104
D/LeakCanary: Watching instance of android.widget.PopupWindow$PopupDecorView (android.widget.PopupWindow$PopupDecorView received View#onDetachedFromWindow() callback) with key b38cb009-bf53-418e-887e-8cc16b63e638
E/CallViewModel: im.tox.tox4j.av.exceptions.ToxavSendFrameException: Error code: FRIEND_NOT_IN_CALL
E/CallViewModel: im.tox.tox4j.av.exceptions.ToxavSendFrameException: Error code: FRIEND_NOT_IN_CALL
E/CallViewModel: im.tox.tox4j.av.exceptions.ToxavSendFrameException: Error code: FRIEND_NOT_IN_CALL
E/CallViewModel: im.tox.tox4j.av.exceptions.ToxavSendFrameException: Error code: FRIEND_NOT_IN_CALL
E/EventListenerCallbacks: callState 25F0EE80 [FINISHED]

Tried to merge current branch with this functionality to no avail...  any ideas ?
I understand that function for implementing to recevie calls is not yet implemented.. is there?

**Comment by robinlinden** [comment]
No, this branch doesn't have accepting incoming calls yet, but outgoing calls work. It needs some minor additional work before merging, but the functionality works if you want to try it yourself.

If you need help with it or have any questions, you can find me as `robinli` in `#atox` on freenode.

**Comment by nibytes** [comment]
Are you need help?

**Comment by robinlinden** [comment]
@nibytes I've just been a bit busy and not had time to finish this properly. I think this works well enough as-is (I've sent a nightly containing this to a bunch of people to get some feedback on the quality), so the plan is to make the notification text reasonable, merge this, and open another PR adding support for accepting incoming calls. :P

**Pull request merged**
