### PR TITLE
Add changelog for the coming 0.7.3 release

### PR DESCRIPTION
**Pull request by robinlinden**

### CODE REVIEW

**Review by roihershberg — CHANGES_REQUESTED** [review]
Maybe also include `Updated to Toxcore 0.2.15` like in `0.7.0` changelog?
https://github.com/evilcorpltd/aTox/blob/96e69212eccceadabc3636b274654c8825967e10/fastlane/metadata/android/en-US/changelogs/10.txt#L8

Or it doesn't matter anymore?

**Comment by robinlinden** [comment]
Ah, good catch! I overlooked the commit that did that. :x Will add!

**Comment by robinlinden** [comment]
Added it, and also reworded the first line to fit better with the rest of the changelog.

**Review by roihershberg — APPROVED** [review]
Looks good!

**Pull request merged**
