### PR TITLE
Update to Toxcore 0.2.15

### PR DESCRIPTION
**Pull request by robinlinden**

### CODE REVIEW

**Review by roihershberg — APPROVED** [review]
🎉

**Comment by robinlinden** [comment]
Yeah, you're right. :P That's also tested in CI, so it'll block merging of this until that's fixed (but GH Actions was broken when I opened this PR.)

I also need to update it to bump us to 0.2.15 now. 0.2.14 had an issue with excessive logging (that wouldn't affect us, but still.) :D

**Comment by roihershberg** [comment]
Yeah, the GitHub Actions was a weird thing.

**Comment by robinlinden** [comment]
@roihershberg Fixed the missing bump in Dependencies.kt and jumped past 0.2.14 to 0.2.15. :P I've heard from other people that this release reduced CPU-usage noticeably, so this should be great!

**Comment by roihershberg** [comment]
That's great!

**Pull request merged**
