### PR TITLE
Upload debug apk in CI builds

### PR DESCRIPTION
**Pull request by roihershberg**
Sign the debug apk with a custom debug keystore which is the default one and then upload it as an artifact.

### CODE REVIEW

**Comment by robinlinden** [comment]
I think this looks good, but where did the keystore come from? Did you generate it locally? Curious since the date's from 2019. :P

Output from `keytool -v -list`

```
Keystore type: jks
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: androiddebugkey
Creation date: Jun 25, 2019
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: C=US, O=Android, CN=Android Debug
Issuer: C=US, O=Android, CN=Android Debug
Serial number: 1
Valid from: Tue Jun 25 06:47:22 CEST 2019 until: Thu Jun 17 06:47:22 CEST 2049
Certificate fingerprints:
         MD5:  1F:90:14:61:34:26:FC:70:8D:BA:62:F0:AC:90:CB:55
         SHA1: 57:08:6B:96:AA:AE:2E:38:45:96:CA:9C:71:2D:59:A1:E4:92:69:21
         SHA256: F1:0E:FD:77:09:65:D6:BA:76:AE:FE:6A:B5:C7:B3:CA:F6:D6:BA:47:4C:F3:FD:C4:53:04:0C:DC:E1:AB:B8:E8
Signature algorithm name: SHA1withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 1


*******************************************
*******************************************



Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -
srckeystore debug.keystore -destkeystore debug.keystore -deststoretype pkcs12".
```

**Comment by roihershberg** [comment]
Nope. It's from the repo I sent you in IRC. I tried to generate one myself but I got an error that HmacPBESha256 algorithm is not available. I looked on it and found that it needs JDK 16+. So I just used this keystore. Maybe I should check if I used a different JDK instead on the one that Android Studio installed. But still do you want me to generate one on my own with the info I found in the internet that is required for a debug keystore or just use this one?

**Comment by roihershberg** [comment]
If I can just set that `Signature algorithm name: SHA1withRSA` line myself then I think this will solve it.

**Comment by robinlinden** [comment]
Not a huge fan of grabbing a keystore from a random repository online. I generated one while checking this PR out, so how about I check that one in?

**Comment by roihershberg** [comment]
Yeah go for it

**Comment by robinlinden** [comment]
Keytool info for the new key:

```
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: androiddebugkey
Creation date: Dec 29, 2021
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: C=US, O=Android, CN=Android Debug
Issuer: C=US, O=Android, CN=Android Debug
Serial number: 1
Valid from: Wed Dec 29 18:29:34 CET 2021 until: Fri Dec 22 18:29:34 CET 2051
Certificate fingerprints:
         MD5:  F2:8E:11:FD:05:E3:A1:4A:22:B1:1D:6F:4D:47:6C:CD
         SHA1: F7:C2:1E:34:37:63:AD:A5:E4:4E:9D:AB:01:4C:98:58:8C:AA:8B:51
         SHA256: 3C:FF:FC:B6:A0:9A:FB:D6:31:C7:BC:66:6E:72:F1:CF:BC:FD:62:EA:B2:BD:BE:4C:C3:A6:9B:06:40:FF:22:EB
Signature algorithm name: SHA1withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 1
```

I guess all newly generated keystores use the not-proprietary key format, so that's a nice bonus. :P

**Comment by roihershberg** [comment]
Yes! It's much better

**Comment by robinlinden** [comment]
Can you double-check that this still works for you? Since apparently there's a new key format and everything. :P

**Review by robinlinden — APPROVED** [review]
Seems to work fine!
Allows mixing CI-built apks with locally built ones and everything, so makes testing new things more convenient.

**Pull request merged**
