### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by robinlinden**

### CODE REVIEW

**Review by roihershberg — CHANGES_REQUESTED** [review]
I updated the Appcompat library and fixed the error. Is it possible to grant me permission to this specific PR to push the commit like you pushed to a PR I opened a while ago?

**Comment by robinlinden** [comment]
Only maintainers can push to open PRs. There's a setting `Allow edits and access to secrets by maintainers` when you open a PR. :x If you push to a branch, I add it to this PR, or you can open a separate PR after this one is merged. What would you prefer?

**Comment by roihershberg** [comment]
Yeah I'll just push to a temporary branch and link the commit.

**Comment by roihershberg** [comment]
https://github.com/roihershberg/aTox/commit/07ae8dde2091f18a8681bc239bce26bef558fa5d

**Comment by robinlinden** [comment]
Good job fixing the error!

**Comment by roihershberg** [comment]
It's more of a hack than a fix. Those errors are what happens when we use a material component like `ShapeableImageView` without the theme of the app actually inheriting from `MaterialComponents` instead of `AppCompat`. It can't find some `ColorStateList` that is defined only in `MaterialComponents` theme.
We have 3 options:
1. Keep it in version 1.3.1 until we switch to material theme (in the redesign).
2. Switch to material theme now.
3. Merge the hack.

**Comment by robinlinden** [comment]
Probably 3 and then 2 or 1, depending on how we feel about it. AppCompat is mostly code that has nothing to do with Material design, so I'd like to keep it up to date to make sure we always have the latest bugfixes and improvements. :P

**Comment by roihershberg** [comment]
OK. We'll just need to put this hack on every `AvatarImageView` we create but that's OK.

**Pull request merged**
