### PR TITLE
Download NDK only if doesn't exist in ANDROID_NDK_HOME + Update NDK to r21e

### LINKED ISSUE #935: Support specifying the NDK location using an env var
Right now we always require it to be in 
https://github.com/evilcorpltd/aTox/blob/1c4d05637a9c242e67b7b9326cac14eb91ac16cc/scripts/android.mk#L1
which is pretty silly, since I already have an NDK elsewhere for e.g. the Bazel build. It would be nice to support using the same NDK for the from-source build. `ATOX_NDK_HOME`? Reusing `ANDROID_NDK_HOME`?

### PR DESCRIPTION
**Pull request by roihershberg**

### CODE REVIEW

**Comment by roihershberg** [comment]
It's my first time I have ever touched a makefile. Many mistakes...

**Comment by robinlinden** [comment]
Do you think you can have a look at a simpler version of this for 0.7.1 and we'll have a look at merging this after that release? All FDroid needs is to be able to point at a specific NDK using ANDROID_NDK_HOME. So no validation or anything. Something similar to 7161d39faa2ec989336171e4da4713cb32829548.

For CI, we don't have to switch to the GitHub NDK or anything, just unset ANDROID_NDK_HOME if they've got it set to a version aTox doesn't build with yet.

I'd like to release 0.7.1 ASAP since Android KitKat literally can't run aTox 0.7.0, but we need something like this for FDroid before releasing it. :x

**Comment by roihershberg** [comment]
OK. Yeah I'll try to make a new version that is simpler. The problem is that we will detect the ANDROID_NDK_HOME and it will fail with the CI because of the weirdness of `libvpx` building. The version of the NDK in CI is also exactly the version that we need. So how can we ignore GitHub CI's ANDROID_NDK_HOME while accepting F-Droid CI's?

**Comment by robinlinden** [comment]
> So how can we ignore GitHub CI's ANDROID_NDK_HOME while accepting F-Droid CI's?

Sorry, I wasn't very clear in my previous comment. :P
`unset ANDROID_NDK_HOME`
before running the scripts (same CI step!) should do it!

**Comment by roihershberg** [comment]
Yeah forgot that we can edit the CI itself XD

**Comment by roihershberg** [comment]
How about that we'll close this? The current behavior seems fine to me and that's exactly what you'll find in other projects. It's the responsibility of the user to provide a valid NDK and to set up the env var correctly.

**Comment by robinlinden** [comment]
Yeah, I agree. Trying to maintain this will be a chore when updating the NDK. :P It's on the user to provide a valid NDK of a version we support.

**Comment by roihershberg** [comment]
Basic functionality has been merged in #957 and we decided to keep it as it is as can be seen above.

**Pull request closed without merging**
