### PR TITLE
Migrate from azure pipelines to github action

### LINKED ISSUE #465: Port the Azure pipelines to GitHub actions
They're about equally good, but having them all in GitHub actions is more convenient for me.

### PR DESCRIPTION
**Pull request by amirmahdi-nsh**
Hi
This Pull request should solve https://github.com/evilcorpltd/aTox/issues/465.
if one failed remnant jobs will cancel too. To avoid this, You can add `fail-fast: false` to strategy. [Source](https://github.community/t/why-a-matrix-step-will-be-canceled-if-another-one-failed/16184/4#M617)

I think `max-parallel: 6` is unnecessary but I prefer to not add another one commit.

Thank you for working on increase freedom and privacy :))

Resolves #465

### CODE REVIEW

**Comment by robinlinden** [comment]
This is awesome, thank you so much! :)
Looks like it failed because of actual issues found by the lint job. Very strange that Azure DevOps didn't find them. :P
Want to have a look at the lint issues? If not, I can fix them and rebase this commit for you.

**Comment by amirmahdi-nsh** [comment]
> Want to have a look at the lint issues?

I'm so sorry, because I am not a Kotlin programmer yet(But maybe I'll be :P). Please fix that.

> As for adding more commits...

Thanks for guides but in this situation not needed because I think `max-parallel: 6` does not cause any problem, It's just unnecessary :)

Thanks

**Comment by robinlinden** [comment]
There we go. Added a commit fixing the lint problems. Thank you again so much! :D

**Review by robinlinden — APPROVED** [review]

**Comment by amir28** [comment]
You're Welcome ;)

**Pull request merged**
