### PR TITLE
Fix API 19 crashing because of AudioAttributes missing

### PR DESCRIPTION
**Pull request by roihershberg**

### CODE REVIEW

**Comment by robinlinden** [comment]
I don't get it. The before and after are identical? Both call `setSound(Uri, AudioAttributes)` and both pass `null` as the AudioAttributes on API 21 and lower. What is the crash and what does this actually fix?

**Comment by roihershberg** [comment]
The before instantiates a variable of the type `AudioAttributes?` which the API doesn't support that and crashes and the after is passing a `null` directly to the method so no variable of type `AudioAttributes` is created.

**Comment by robinlinden** [comment]
Ah, right. Fair enough. :D I thought `missing` in this case was that the API didn't accept null for some reason. Good find!

**Comment by roihershberg** [comment]
Thanks

**Comment by robinlinden** [comment]
We'll have to make a new release with this fix since this is broken in what's on GPlay. :x

**Review by robinlinden — APPROVED** [review]

**Comment by roihershberg** [comment]
Oh XD

**Comment by robinlinden** [comment]
rip old Android. Good thing almost no one uses it. :D

**Comment by roihershberg** [comment]
Yeah XD

**Pull request merged**
