### PR TITLE
Expand clickable area of contact header in chat fragment

### PR DESCRIPTION
**Pull request by roihershberg**

### CODE REVIEW

**Review by robinlinden — COMMENTED** [review]
I don't think the app bar should be throwing a shadow on the system toolbar. See https://material.io/components/app-bars-top for examples of how this can look.

**Comment by roihershberg** [comment]
Didn't notice that. It seems that AppBarLayout indeed needs a CoordinatorLayout. Just trying to figure out how to combine a CoordinatorLayout with ConstraintLayout and in general the current layout.

**Comment by robinlinden** [comment]
Or should they be? I'm not 100% sure what the recommendation actually is... I just reacted because I don't think I've seen it in any apps before.

WhatsApp is completely "flat". Telegram has a different color from the system toolbar, but the same elevation, and only throws a shadow down towards the rest of the app. Signal appears to be "flat" as well. I guess it's at the very least uncommon to throw a shadow over the system toolbar as well.

**Comment by roihershberg** [comment]
Yeah it shouldn't happen. And changing to CoordinatorLayout doesn't seem to solve it.

**Comment by roihershberg** [comment]
Should be fixed now

**Pull request merged**
